name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      env:
        TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
      run: python main.py
